---
# Install hadoop
- block:
  - name: Get hadoop 
    get_url:
      url=http://mirror.switch.ch/mirror/apache/dist/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz 
      dest=/usr/local/hadoop-{{ hadoop_version }}.tar.gz

  - name: unzip hadoop
    unarchive: 
      copy=no 
      src=/usr/local/hadoop-{{ hadoop_version }}.tar.gz 
      dest=/usr/local/
      owner={{ hadoop_user }} 
      group=hadoop
      creates=/usr/local/hadoop-{{ hadoop_version }}

  - name: set user and priviliges on hadoop
    file: path=/usr/local/hadoop-{{ hadoop_version }} owner={{ hadoop_user }} group=hadoop recurse=yes

  - name: make hadoop symlink
    file: src=/usr/local/hadoop-{{ hadoop_version }} dest=/usr/local/hadoop owner={{ hadoop_user }} group=hadoop state=link

  - name: make logs directory
    file: path=/usr/local/hadoop-{{ hadoop_version }}/logs state=directory
    
  tags: 
    - downloads

