---
- block:
  - name: format hdfs
    command: /usr/local/hadoop/bin/hdfs namenode -format -force -nonInteractive
    become: yes
    become_user: hadoop
    when: hdfs_reformat and inventory_hostname in groups['spark_masters']

  - name: start hadoop namenode
    supervisorctl: name=hdfs_namenode state=started config=/etc/supervisor/supervisord.conf
    environment: "{{ hadoop_env }}"
    when: inventory_hostname in groups['spark_masters']

  - name: start hadoop datanode
    supervisorctl: name=hdfs_datanode state=started config=/etc/supervisor/supervisord.conf
    environment: "{{ hadoop_env }}"
    when: inventory_hostname in groups['spark_slaves']

  tags: 
    - start-service
