---

- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
  - name: Create a new spark master instance 
    os_server:
      state: "{{ instance_state }}"
      name: spark-master
      image: c18fe24e-210b-47d4-b347-4b0beff4ec50
      key_name: "{{ key_name }}"
      timeout: 200
      flavor: 1cpu-4ram-hpc
      nics:
        - net-id: "{{ network_id }}"
      security_groups: spark,default
      meta:
        hostname: spark-master
        ansible_host_groups: spark_masters,default
    register: spark_master

  - name: Create a new spark slaves
    os_server:
      state: "{{ instance_state }}"
      name: "{{ item }}"
      image: c18fe24e-210b-47d4-b347-4b0beff4ec50
      key_name: "{{ key_name }}"
      timeout: 200
      flavor: 1cpu-4ram-hpc
      nics:
        - net-id: "{{ network_id }}"
      security_groups: spark,default
      meta:
        hostname: "{{ item }}"
        ansible_host_groups: spark_slaves,default
    register: spark_slaves
    with_sequence: 
      start=1
      end="{{ nbr_of_slaves }}"
      format=spark-slave%02x
