---
- name: format hdfs
  command: /usr/local/hadoop/bin/hadoop namenode -format -force -nonInteractive
  when: hdfs_reformat
  tags: 
    - start-service

- block:
  - name: stop hadoop (if running)
    command: /usr/local/hadoop/sbin/stop-dfs.sh

  - name: start hadoop
    command: /usr/local/hadoop/sbin/start-dfs.sh

  tags: 
    - start-service
