---
- block:
  - name: format hdfs
    command: /usr/bin/hadoop namenode -format -force -nonInteractive
    when: hdfs_reformat

  - name: stop hadoop (if running)
    command: /usr/local/hadoop/sbin/stop-dfs.sh

  - name: start hadoop
    command: /usr/local/hadoop/sbin/start-dfs.sh

  tags: 
    - start-service
