---
- name: update supervisor
  become: yes
  become_user: root
  command: /usr/bin/supervisorctl update

- name: restart supervisor
  become: yes
  become_user: root
  service: name=supervisor state=restarted
  
