---
# General tasks
- block:
  - name: install java
    apt: name=openjdk-7-jre state=present update_cache=yes

  - name: disable net.ipv6.conf.all.disable_ipv6
    sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present

  - name: disable net.ipv6.conf.default.disable_ipv6
    sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 state=present

  - name: disable net.ipv6.conf.lo.disable_ipv6
    sysctl: name=net.ipv6.conf.lo.disable_ipv6 value=1 state=present

  - name: distribute host file
    template: src=templates/hosts.j2 dest=/etc/hosts

  tags:
    - general

# Setup ssh keys and user accounts
- block: 
  - name: create hadoop group
    group: name=hadoop state=present

  - name: create hadoop user
    user: name={{ hadoop_user }} comment="Hadoop user" group=hadoop shell=/bin/bash

  - name: deploy authorized keys
    authorized_key: user={{ item }} key="{{ ssh_public_key_content }}"
    with_items:
      - "{{ user }}"
      - "{{ hadoop_user }}"

  - name: deploy ssh-keys
    copy: src={{ssh_keys_to_use}} dest=/home/{{ item }}/.ssh/
    with_items:
      - "{{ user }}"
      - "{{ hadoop_user }}"

  - name: distribute ssh config
    template: src=templates/config.j2 dest=/home/{{ item }}/.ssh/config
    with_items:
      - "{{ user }}"
      - "{{ hadoop_user }}"

  - name: add hadoop and spark binaries to path for hadoop user
    lineinfile:
      dest=/home/{{ item }}/.bashrc 
      state=present insertafter=EOF 
      line="export PATH=$PATH:/usr/local/hadoop/bin/:/usr/local/spark/bin/"
      create=true
    with_items: "{{core_user_list}}"
  
  - name: create user accounts
    user: name={{ item.key }} group=hadoop append=yes password={{ item.value }}
    with_dict: "{{ user_passwords }}"

  tags:
    - user-accounts
    